"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-08-20 19:44:00.816955

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables whose rows are immutable: a BEFORE UPDATE OR DELETE trigger raises.
IMMUTABLE_TABLES: tuple[str, ...] = (
    "ledger_events",
    "ledger_entries",
    "feature_snapshots",
    "assessments",
    "decisions",
    "decision_reasons",
)

# Native enum types created by this migration — dropped explicitly on downgrade so the
# reverse is clean (Alembic does not drop enum types automatically).
ENUM_TYPES: tuple[str, ...] = (
    "user_role",
    "application_status",
    "consent_status",
    "source_type",
    "source_connection_status",
    "evidence_event_type",
    "assessment_kind",
    "calibration_status",
    "finding_severity",
    "policy_status",
    "decision_action",
    "review_status",
    "review_outcome",
    "model_status",
    "outcome_label",
    "notice_type",
    "notice_channel",
    "notice_status",
    "job_type",
    "job_status",
)

_IMMUTABILITY_FUNCTION = "aperture_forbid_mutation"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('applicants',
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_applicants_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applicants')),
    sa.UniqueConstraint('tenant_id', 'external_ref', name='uq_applicants_tenant_id_external_ref')
    )
    op.create_index(op.f('ix_applicants_tenant_id'), 'applicants', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.Enum('DECISION', 'INGEST', 'REDECISION', 'NOTICE', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD', name='job_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_jobs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_status_run_after', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'ACTIVE', 'RETIRED', name='model_status'), nullable=False),
    sa.Column('calibration_status', sa.Enum('CALIBRATED', 'UNCALIBRATED', 'NOT_APPLICABLE', name='calibration_status'), nullable=False),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_model_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_model_versions_tenant_id_name_version')
    )
    op.create_index(op.f('ix_model_versions_tenant_id'), 'model_versions', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('CREDIT_POLICY_OWNER', 'CREDIT_ANALYST', 'FRAUD_REVIEWER', 'AUDITOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_id_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('applications',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROCESSING', 'DECIDED', 'REFERRED', 'CLOSED', name='application_status'), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=True),
    sa.Column('requested_amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('requested_tenor_months', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_applications_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_applications_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_applicant_id', 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_table('consents',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'REVOKED', 'EXPIRED', name='consent_status'), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_ref', sa.String(length=512), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_consents_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consents_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index('ix_consents_applicant_id', 'consents', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('entry_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ledger_entries_actor_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ledger_entries_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('tenant_id', 'seq', name='uq_ledger_entries_tenant_id_seq')
    )
    op.create_index(op.f('ix_ledger_entries_tenant_id'), 'ledger_entries', ['tenant_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'LIVE', 'ARCHIVED', name='policy_status'), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_policy_versions_created_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policy_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_policy_versions_tenant_id_version')
    )
    op.create_index(op.f('ix_policy_versions_tenant_id'), 'policy_versions', ['tenant_id'], unique=False)
    op.create_index('uq_policy_versions_one_live_per_tenant', 'policy_versions', ['tenant_id'], unique=True, postgresql_where=sa.text("status = 'LIVE'"))
    op.create_table('feature_snapshots',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('null_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_feature_snapshots_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_feature_snapshots_application_id_applications')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_feature_snapshots_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots'))
    )
    op.create_index('ix_feature_snapshots_applicant_id_as_of', 'feature_snapshots', ['applicant_id', 'as_of'], unique=False)
    op.create_index('ix_feature_snapshots_input_hash', 'feature_snapshots', ['input_hash'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_tenant_id'), 'feature_snapshots', ['tenant_id'], unique=False)
    op.create_table('source_connections',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('consent_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('BANK', 'UPI', 'UTILITY', 'TELECOM', 'BUREAU', name='source_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'FAILED', 'REVOKED', name='source_connection_status'), nullable=False),
    sa.Column('external_account_ref', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_source_connections_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], name=op.f('fk_source_connections_consent_id_consents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_connections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_connections'))
    )
    op.create_index('ix_source_connections_applicant_id', 'source_connections', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_source_connections_tenant_id'), 'source_connections', ['tenant_id'], unique=False)
    op.create_table('assessments',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('feature_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('RISK', 'AFFORDABILITY', 'COVERAGE', 'MANIPULATION', name='assessment_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('calibration_status', sa.Enum('CALIBRATED', 'UNCALIBRATED', 'NOT_APPLICABLE', name='calibration_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_assessments_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_assessments_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_assessments_model_version_id_model_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_assessments_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index('ix_assessments_feature_snapshot_id', 'assessments', ['feature_snapshot_id'], unique=False)
    op.create_index(op.f('ix_assessments_tenant_id'), 'assessments', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('feature_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('policy_version_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'APPROVE_STARTER', 'DECLINE', 'REFER', name='decision_action'), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_limit_paise', sa.BigInteger(), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fired_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_decisions_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_decisions_application_id_applications')),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_decisions_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_decisions_policy_version_id_policy_versions')),
    sa.ForeignKeyConstraint(['superseded_by'], ['decisions.id'], name=op.f('fk_decisions_superseded_by_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_decisions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_applicant_id_created_at', 'decisions', ['applicant_id', 'created_at'], unique=False)
    op.create_index('ix_decisions_application_id', 'decisions', ['application_id'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('source_connection_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('TRANSACTION', 'PAYMENT', 'BALANCE', 'BUREAU_RECORD', 'OTHER', name='evidence_event_type'), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_ledger_events_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], name=op.f('fk_ledger_events_source_connection_id_source_connections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ledger_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_events')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_ledger_events_tenant_id_idempotency_key')
    )
    op.create_index('ix_ledger_events_applicant_id_occurred_at', 'ledger_events', ['applicant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_ledger_events_tenant_id'), 'ledger_events', ['tenant_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('source_connection_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_ref', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_source_snapshots_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], name=op.f('fk_source_snapshots_source_connection_id_source_connections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_snapshots_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots'))
    )
    op.create_index('ix_source_snapshots_source_connection_id', 'source_snapshots', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_tenant_id'), 'source_snapshots', ['tenant_id'], unique=False)
    op.create_table('decision_reasons',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_reasons_decision_id_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_decision_reasons_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_reasons'))
    )
    op.create_index('ix_decision_reasons_decision_id', 'decision_reasons', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_reasons_tenant_id'), 'decision_reasons', ['tenant_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('queue', sa.String(length=64), server_default=sa.text("'default'"), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'RESOLVED', name='review_status'), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVED', 'DECLINED', 'ESCALATED', name='review_outcome'), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_human_reviews_application_id_applications')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_human_reviews_decision_id_decisions')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_human_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_human_reviews_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_reviews'))
    )
    op.create_index('ix_human_reviews_application_id', 'human_reviews', ['application_id'], unique=False)
    op.create_index('ix_human_reviews_status', 'human_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_human_reviews_tenant_id'), 'human_reviews', ['tenant_id'], unique=False)
    op.create_table('manipulation_findings',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finding_severity'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_manipulation_findings_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_manipulation_findings_assessment_id_assessments')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_manipulation_findings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manipulation_findings'))
    )
    op.create_index('ix_manipulation_findings_assessment_id', 'manipulation_findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_manipulation_findings_tenant_id'), 'manipulation_findings', ['tenant_id'], unique=False)
    op.create_table('notices',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('notice_type', sa.Enum('DECISION', 'RECOURSE_REQUEST', name='notice_type'), nullable=False),
    sa.Column('language', sa.String(length=8), server_default=sa.text("'en'"), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'POST', name='notice_channel'), nullable=True),
    sa.Column('status', sa.Enum('RENDERED', 'SENT', 'FAILED', name='notice_status'), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('rendered_ref', sa.String(length=512), nullable=True),
    sa.Column('llm_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_notices_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_notices_application_id_applications')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_notices_decision_id_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notices_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notices'))
    )
    op.create_index('ix_notices_decision_id', 'notices', ['decision_id'], unique=False)
    op.create_index(op.f('ix_notices_tenant_id'), 'notices', ['tenant_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Enum('PERFORMING', 'DELINQUENT', 'DEFAULTED', 'PAID_OFF', 'WRITTEN_OFF', name='outcome_label'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('principal_paise', sa.BigInteger(), nullable=True),
    sa.Column('outstanding_paise', sa.BigInteger(), nullable=True),
    sa.Column('loss_paise', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], name=op.f('fk_outcomes_applicant_id_applicants')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_outcomes_application_id_applications')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_outcomes_decision_id_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_outcomes_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_index('ix_outcomes_application_id', 'outcomes', ['application_id'], unique=False)
    op.create_index('ix_outcomes_decision_id', 'outcomes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_outcomes_tenant_id'), 'outcomes', ['tenant_id'], unique=False)
    op.create_table('recourse_options',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_change', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('projected_action', sa.Enum('APPROVE', 'APPROVE_STARTER', 'DECLINE', 'REFER', name='decision_action'), nullable=True),
    sa.Column('projected_limit_paise', sa.BigInteger(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_recourse_options_decision_id_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_recourse_options_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recourse_options'))
    )
    op.create_index('ix_recourse_options_decision_id', 'recourse_options', ['decision_id'], unique=False)
    op.create_index(op.f('ix_recourse_options_tenant_id'), 'recourse_options', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Immutability: block UPDATE/DELETE on append-only, audit-critical tables. ---
    # Convention is not a control; the database enforces it.
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION {_IMMUTABILITY_FUNCTION}() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'Row in immutable table % cannot be % (append-only)',
                TG_TABLE_NAME, lower(TG_OP)
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            f"FOR EACH ROW EXECUTE FUNCTION {_IMMUTABILITY_FUNCTION}();"
        )


def downgrade() -> None:
    # Drop immutability triggers and the shared function first.
    for table_name in IMMUTABLE_TABLES:
        op.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name};"
        )
    op.execute(f"DROP FUNCTION IF EXISTS {_IMMUTABILITY_FUNCTION}();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recourse_options_tenant_id'), table_name='recourse_options')
    op.drop_index('ix_recourse_options_decision_id', table_name='recourse_options')
    op.drop_table('recourse_options')
    op.drop_index(op.f('ix_outcomes_tenant_id'), table_name='outcomes')
    op.drop_index('ix_outcomes_decision_id', table_name='outcomes')
    op.drop_index('ix_outcomes_application_id', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_notices_tenant_id'), table_name='notices')
    op.drop_index('ix_notices_decision_id', table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_manipulation_findings_tenant_id'), table_name='manipulation_findings')
    op.drop_index('ix_manipulation_findings_assessment_id', table_name='manipulation_findings')
    op.drop_table('manipulation_findings')
    op.drop_index(op.f('ix_human_reviews_tenant_id'), table_name='human_reviews')
    op.drop_index('ix_human_reviews_status', table_name='human_reviews')
    op.drop_index('ix_human_reviews_application_id', table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_decision_reasons_tenant_id'), table_name='decision_reasons')
    op.drop_index('ix_decision_reasons_decision_id', table_name='decision_reasons')
    op.drop_table('decision_reasons')
    op.drop_index(op.f('ix_source_snapshots_tenant_id'), table_name='source_snapshots')
    op.drop_index('ix_source_snapshots_source_connection_id', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_ledger_events_tenant_id'), table_name='ledger_events')
    op.drop_index('ix_ledger_events_applicant_id_occurred_at', table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index('ix_decisions_application_id', table_name='decisions')
    op.drop_index('ix_decisions_applicant_id_created_at', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_assessments_tenant_id'), table_name='assessments')
    op.drop_index('ix_assessments_feature_snapshot_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_source_connections_tenant_id'), table_name='source_connections')
    op.drop_index('ix_source_connections_applicant_id', table_name='source_connections')
    op.drop_table('source_connections')
    op.drop_index(op.f('ix_feature_snapshots_tenant_id'), table_name='feature_snapshots')
    op.drop_index('ix_feature_snapshots_input_hash', table_name='feature_snapshots')
    op.drop_index('ix_feature_snapshots_applicant_id_as_of', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('uq_policy_versions_one_live_per_tenant', table_name='policy_versions', postgresql_where=sa.text("status = 'LIVE'"))
    op.drop_index(op.f('ix_policy_versions_tenant_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_ledger_entries_tenant_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index('ix_consents_applicant_id', table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index('ix_applications_applicant_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_versions_tenant_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index('ix_jobs_status_run_after', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_applicants_tenant_id'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_table('tenants')
    # ### end Alembic commands ###

    # Drop native enum types last (tables that referenced them are gone).
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name};")
